In [2]:
import pandas as pd
import numpy as np
import csv
import random
from math import sqrt
from math import pi
from math import exp
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal

In [3]:
def mean(dataset):
    mean_new = []
    for i in range(4):
        mean_new.append(dataset.iloc[:,i].mean())
    return mean_new

In [4]:
def var(dataset):
    var_new = []
    for i in range(4):
        var_new.append(dataset.iloc[:,i].var())
    return var_new

In [5]:
def predict(dataset):
    predicted = []
    for index , row in dataset.iterrows():
        probabilities = []
        mylist = [row['sepal length(cm)'] , row['sepal width(cm)'], row['petal length(cm)'] , row['petal width(cm)']]
        probabilities.append(normal_0.pdf(mylist))
        probabilities.append(normal_1.pdf(mylist))
        probabilities.append(normal_2.pdf(mylist))
        maximum = probabilities.index(max(probabilities))
        predicted.append(maximum)
    return predicted

In [6]:
def accuracy(actual , predicted):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predicted[i]:
            correct += 1
    return ((correct / len(actual)) * 100)

In [7]:
def confusion(actual , predicted):
    mtrx =np.array([[0,0,0],[0,0,0],[0,0,0]])
    for x in range(len(actual)):
        i = actual[x]
        j = predicted[x]
        mtrx[i][j] +=1
    return mtrx

In [8]:
def covar(dataset):
    for i in range(4):
        for j in range(4):
            if i != j:
                dataset.iloc[i,j] = 0
    return dataset

In [9]:
data = pd.read_csv("iris.csv",header=None)
data.columns=['sepal length(cm)','sepal width(cm)','petal length(cm)','petal width(cm)','class']
data.loc[data['class'] == 'Iris-setosa'     , 'class'] = 0
data.loc[data['class'] == 'Iris-versicolor' , 'class'] = 1
data.loc[data['class'] == 'Iris-virginica'  , 'class'] = 2

In [10]:
data.tail(10)

sepal length(cm)  sepal width(cm)  petal length(cm)  petal width(cm)  \
140               6.7              3.1               5.6              2.4   
141               6.9              3.1               5.1              2.3   
142               5.8              2.7               5.1              1.9   
143               6.8              3.2               5.9              2.3   
144               6.7              3.3               5.7              2.5   
145               6.7              3.0               5.2              2.3   
146               6.3              2.5               5.0              1.9   
147               6.5              3.0               5.2              2.0   
148               6.2              3.4               5.4              2.3   
149               5.9              3.0               5.1              1.8   

    class  
140     2  
141     2  
142     2  
143     2  
144     2  
145     2  
146     2  
147     2  
148     2  
149     2

In [11]:
data_0 = data[data['class'] == 0]   
data_0_train = data_0.sample(frac = 0.7)  #70% of each class which is 35 is for training other 15 is for test


data_1 = data[data['class'] == 1]
data_1_train = data_1.sample(frac = 0.7)


data_2 = data[data['class'] == 2]
data_2_train = data_2.sample(frac = 0.7)


mean_0 = mean(data_0_train)
mean_1 = mean(data_1_train)
mean_2 = mean(data_2_train)

cov_0 = data_0.cov()
cov_1 = data_1.cov()
cov_2 = data_2.cov()

data_0_test = data_0.drop(data_0_train.index)
data_1_test = data_1.drop(data_1_train.index)
data_2_test = data_2.drop(data_2_train.index)

In [12]:
normal_0 = multivariate_normal(mean_0 , cov_0)
normal_1 = multivariate_normal(mean_1 , cov_1)
normal_2 = multivariate_normal(mean_2 , cov_2)

In [13]:
data_train = pd.concat([data_0_train , data_1_train , data_2_train])
data_test  = pd.concat([data_0_test  , data_1_test  , data_2_test ])

actual = []
for index , row in data_train.iterrows():
    actual.append(row['class'])
    
preds =predict(data_train)

acc = accuracy(actual , preds)
print("accuracy over trainig data is : {} %".format(acc))

actual = []
for index , row in data_test.iterrows():
    actual.append(row['class'])
    
preds =predict(data_test)

acc = accuracy(actual , preds)
print("accuracy over test data is    : {} %".format(acc))

conf = confusion(actual , preds)
print(conf)

accuracy over trainig data is : 98.09523809523809 %
accuracy over test data is    : 97.77777777777777 %
[[15  0  0]
 [ 0 14  1]
 [ 0  0 15]]


# 4-fold cross validation

In [23]:
data = pd.read_csv("iris.csv",header=None)
data.columns=['sepal length(cm)','sepal width(cm)','petal length(cm)','petal width(cm)','class']
data.loc[data['class'] == 'Iris-setosa'     , 'class'] = 0
data.loc[data['class'] == 'Iris-versicolor' , 'class'] = 1
data.loc[data['class'] == 'Iris-virginica'  , 'class'] = 2

In [24]:
data_0 = data[data['class'] == 0]  
data_0_train_a = data_0.sample(n=12)
data_0 = data_0.drop(data_0_train_a.index)

data_0_train_b = data_0.sample(n=12)
data_0 = data_0.drop(data_0_train_b.index)

data_0_train_c = data_0.sample(n=12)
data_0_test = data_0.drop(data_0_train_c.index)
#-----------------------------------------------

data_1 = data[data['class'] == 1]  
data_1_train_a = data_1.sample(n=12)
data_1 = data_1.drop(data_1_train_a.index)

data_1_train_b = data_1.sample(n=12)
data_1 = data_1.drop(data_1_train_b.index)

data_1_train_c = data_1.sample(n=12)
data_1_test = data_1.drop(data_1_train_c.index)

#-----------------------------------------------

data_2 = data[data['class'] == 2]  
data_2_train_a = data_2.sample(n=12)
data_2 = data_2.drop(data_2_train_a.index)

data_2_train_b = data_2.sample(n=12)
data_2 = data_2.drop(data_2_train_b.index)

data_2_train_c = data_2.sample(n=12)
data_2_test = data_2.drop(data_2_train_c.index)
#-----------------------------------------------

In [25]:
cov_0_mtrx = covar(cov_0)
cov_1_mtrx = covar(cov_1)
cov_2_mtrx = covar(cov_2)

normal_0 = multivariate_normal(mean_0 , cov_0_mtrx)
normal_1 = multivariate_normal(mean_1 , cov_1_mtrx)
normal_2 = multivariate_normal(mean_2 , cov_2_mtrx)

In [26]:
data_train = pd.concat([data_0_train_a , data_0_train_b , data_0_train_c , data_1_train_a , data_1_train_b , data_1_train_c , data_2_train_a , data_2_train_b , data_2_train_c])
data_test  = pd.concat([data_0_test  , data_1_test  , data_2_test ])

actual = []
for index , row in data_train.iterrows():
    actual.append(row['class'])
    
preds =predict(data_train)

acc = accuracy(actual , preds)
print("accuracy over trainig data is : {} %".format(acc))

actual = []
for index , row in data_test.iterrows():
    actual.append(row['class'])
    
preds =predict(data_test)

acc = accuracy(actual , preds)
print("accuracy over test data is    : {} %".format(acc))

conf = confusion(actual , preds)
print(conf)

accuracy over trainig data is : 96.29629629629629 %
accuracy over test data is    : 95.23809523809523 %
[[14  0  0]
 [ 0 13  1]
 [ 0  1 13]]
